### ISSUE TITLE
Crash when reading alarms

### ISSUE THREAD

**Issue by ebob9** [ebob9/cg-syslog-apigw#2]
```
Traceback (most recent call last):
  File "./cg-syslog-apigw.py", line 1604, in <module>
    alarm_resp_code = update_parse_alarm(alarm_last_event_date, sdk_vars=sdk_vars)
  File "./cg-syslog-apigw.py", line 628, in update_parse_alarm
    info_string = info_string + key.upper() + ": " + str(value) + " "
UnboundLocalError: local variable 'info_string' referenced before assignment
```

Happens whenever an alarm is parsed with latest version.

**Comment by ebob9** [comment]
Introduced a silly bug when fixing an info_string crash, fixed.
